/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ddcSol from "./DDC.sol";
export type { ddcSol };
export type { DDCStorage } from "./DDCStorage";
export type { ERC721URIStorageUpgradeable } from "./ERC721URIStorageUpgradeable";
export type { IDDC } from "./IDDC";
